package AirVista;

import java.util.HashMap;

public class Booking {

    private String bookingId;      // Unique identifier for each booking
    private String passengerId;    // Passenger ID
    private String flightId;       // Flight ID
    private boolean bookingStatus; // true = active, false = cancelled

    // Static Maps to manage data in memory, these will be replaced with DB interaction
    private static int bookingCounter = 0;
    private static HashMap<String, Booking> bookings = new HashMap<>();
    private static HashMap<String, Integer> passengerCountMap = new HashMap<>();

    // Constructor to create a new booking
    public Booking(Passenger passenger, String flightId) {
        try {
            // Fetch the flight by ID using the predefined function
            Flight flight = Flight.getFlightById(flightId);
            if (flight == null) {
                throw new Exception("Flight with ID " + flightId + " not found.");
            }

            // Check if the passenger is already booked on this flight using the predefined function
            if (isPassengerAlreadyBooked(passenger.getPassengerId(), flightId)) {
                throw new Exception("Passenger already booked on flight " + flightId);
            }

            // Generate the booking ID (this logic will be handled by DB for unique ID generation)
            this.bookingId = generateBookingId(flightId, passenger.getPassengerId());
            this.passengerId = passenger.getPassengerId();
            this.flightId = flightId;
            this.bookingStatus = true;

            // Add the passenger to the flight using the predefined function
            flight.addPassenger(passenger);

            // Update the passenger status
            passenger.setStatus("booked");

            // Increment passenger count for the flight
            incrementPassengerCount(flightId);

            // Store the booking in the map (for in-memory management, replace with DB insert)
            bookings.put(bookingId, this);

            // **Database interaction**: Insert booking record into the database

            System.out.println("Booking successful: " + bookingId);

        } catch (Exception e) {
            System.err.println("Error during booking: " + e.getMessage());
        }
    }

    // Generate a unique booking ID (this would be generated by the database, here it's done manually)
    private static String generateBookingId(String flightId, String passengerId) {
        bookingCounter++;
        return "B" + bookingCounter + "-" + flightId + "-" + passengerId;
    }

    // Check if passenger is already booked for the flight (DB query would replace this check)
    private static boolean isPassengerAlreadyBooked(String passengerId, String flightId) {
        return bookings.values().stream()
                .anyMatch(b -> b.passengerId.equals(passengerId) && b.flightId.equals(flightId));
    }

    // Increment passenger count in-memory (for DB, this would update a count field in the flight record)
    private static void incrementPassengerCount(String flightId) {
        passengerCountMap.put(flightId, passengerCountMap.getOrDefault(flightId, 0) + 1);
    }

    // Cancel all bookings for a flight (DB query to delete bookings for the flight would replace this logic)
    public static void cancelBookingsForFlight(String flightId) {
        bookings.values().stream()
                .filter(b -> b.flightId.equals(flightId) && b.bookingStatus)
                .forEach(b -> b.cancelBooking());

        // **Database interaction**: Delete bookings for this flight from the database
    }

    // Cancel a single booking (for DB, update the status field to 'cancelled')
    public void cancelBooking() {
        if (!bookingStatus) {
            System.err.println("Booking already cancelled: " + bookingId);
            return;
        }
        bookingStatus = false;

        // Remove the passenger from the flight (this is done through the Flight class)
        Flight flight = Flight.getFlightById(this.flightId);
        if (flight != null) {
            flight.removePassenger(this.passengerId); // Remove passenger from the flight
        }

        // **Database interaction**: Update the booking status to 'cancelled' in the database
        System.out.println("Booking " + bookingId + " cancelled.");
    }

    // Getters
    public String getBookingId() {
        return bookingId;
    }

    public boolean getBookingStatus() {
        return bookingStatus;
    }

    // Static method to get all bookings (for DB, fetch all bookings from the database)
    public static HashMap<String, Booking> getAllBookings() {
        return bookings;
    }

    // **Database interaction**:
    // 1. When a booking is created, the information should be saved in a database ( INSERT query).
    // 2. When a booking is cancelled, the status in the database should be updated ( UPDATE query).
    // 3. When a booking is removed, the corresponding booking entry should be deleted ( DELETE query).
}
